name: Update mise Tools

on:
  schedule:
    - cron: "30 8 * * 1-5"
  workflow_dispatch:

permissions: {}

concurrency:
  group: mise-tools-update-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  update-mise-tools:
    uses: navikt/crm-workflows-base/.github/workflows/mise-tools-update.yml@9f0a692a3e63db3c892a38ed79222a0b61b02bde
    permissions:
      contents: write
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}